### ISSUE TITLE
edge module for node.js version v0.11.09

### ISSUE THREAD

**Issue by vjkumarsw** [tjanczuk/edge#105]
I am trying to use the edge module with node webkit. I am using one of the first examples. I get the following error 
Uncaught Error: The edge module has not been pre-compiled for node.js version v0.11.9. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions. I am not sure how to proceed. 
My webkit configuration node-webkit-v0.9.0-rc1-win-ia32. I have posted this question in stackoverflow also.

My code is given below
   var edge = require('edge');
    var helloWorld = edge.func('async (input) => { return ".NET Welcomes " + input.ToString (); }');
helloWorld('JavaScript', function (error, result) {
    if (error) throw error;
    console.log(result);
   });

**Comment by cjones26** [comment]
@vjkumarsw  you're the man!  Works perfectly.

**Comment by sant123** [comment]
Hi, I tried to compile Edge.js with Node.js v6.21 and NW v0.15.1 and I got the following error:

```
D:\santiagoah\informacion\Desktop\Testing Edge\node_modules\edge>nw-gyp configure --target=v0.15.1 --msvs_version=2013 --arch=x64 --python=py
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.13.0
gyp info using node@6.2.1 | win32 | x64
(node:9024) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
gyp info spawn py
gyp info spawn args [ 'C:\\Users\\santiagoah\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2013',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\santiagoah\\informacion\\Desktop\\Testing Edge\\node_modules\\edge\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\santiagoah\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\santiagoah\\.nw-gyp\\0.15.1\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\santiagoah\\.nw-gyp\\0.15.1',
gyp info spawn args   '-Dmodule_root_dir=D:\\santiagoah\\informacion\\Desktop\\Testing Edge\\node_modules\\edge',
gyp info spawn args   '--depth=.',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\santiagoah\\informacion\\Desktop\\Testing Edge\\node_modules\\edge\\build',
gyp info spawn args   '-Goutput_dir=.' ]
(node:9024) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
  File "C:\Users\santiagoah\AppData\Roaming\npm\node_modules\nw-gyp\gyp\gyp_main.py", line 12
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\santiagoah\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:361:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\santiagoah\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "configure" "--target=v0.15.1" "--msvs_version=2013" "--arch=x64" "--python=py"
gyp ERR! cwd D:\santiagoah\informacion\Desktop\Testing Edge\node_modules\edge
gyp ERR! node -v v6.2.1
gyp ERR! nw-gyp -v v0.13.0
gyp ERR! not ok
``` 

¿Any ideas?
