### ISSUE TITLE
Loading my custom node module fails with System.AccessViolationException:

### ISSUE THREAD

**Issue by rajach** [tjanczuk/edge#197]
I am making a call to my custom module and seeing this exception:
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write
 protected memory. This is often an indication that other memory is corrupt.
   at v8.Function.Call(Function* , Local<v8::Value>* , Handle<v8::Object> , Int3
2 , Handle<v8::Value>* )
   at NodejsFuncInvokeContext.CallFuncOnV8Thread()
   at clrActionContext.ActionCallback(Void* data)
   at continueOnV8Thread(uv_async_s* handle, Int32 status)
   at EdgeJs.Edge.NodeStart(Int32 argc, String[] argv)
   at EdgeJs.Edge.<Func>b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Here is my code:
```
#r "C:/node/my_modules/ApiModules/EdgeJs.dll"

using EdgeJs;
using System;
using System.Threading.Tasks;

public class Startup
{
	public async Task<object> Invoke (object input)
	{ 
		var func = Edge.Func(@"
			var fs = require('fs');
			//adding the below line throws the exception
			var gp = require('C:/node/my_modules/ApiModules/GameTestModule.node');
			console.log('hello');
		");
		await func(null); 
		return null; 
	}
}
```
My test module is working with JS outside edge. and I have copied C:\node\node_modules\edge\test\double\double_test\edge to C:/node/my_modules/ApiModules/ directory.  Could this be an issue with edge? How can I find what is causing this?

**Comment by tjanczuk** [comment]
Unfortunately using native Node.js modules is not possible when scripting Node.js code in a .NET application. This is because Edge.js uses a custom build of Node.js which does not contain the symbols required to make native node.js modules run.
