### ISSUE TITLE
Tests failing on Mac, while running clear on Windows

### ISSUE THREAD

**Issue by OlegBoulanov** [tjanczuk/edge#256]
66 passing (1m)
  3 failing

  1) async call from node.js to .net successfuly marshals structured .net exception from .net to node.js:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at done (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runnable.js:221:67)
      at /Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runnable.js:242:9
      at /Users/olegb/Documents/GitHub/edge/test/102_node2net.js:120:13
      at <anonymous>:1:55
      at Context.<anonymous> (/Users/olegb/Documents/GitHub/edge/test/102_node2net.js:111:9)
      at Test.Runnable.run (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runnable.js:233:15)
      at Runner.runTest (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:387:10)
      at /Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:470:12
      at next (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:312:14)
      at /Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:322:7
      at next (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:257:23)
      at Immediate._onImmediate (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:289:5)
      at processImmediate [as _immediateCallback] (timers.js:358:17)

  2) async call from .net to node.js successfuly marshals empty buffer:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at done (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runnable.js:221:67)
      at /Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runnable.js:242:9
      at /Users/olegb/Documents/GitHub/edge/test/103_net2node.js:171:4
      at <anonymous>:1:55
      at Context.<anonymous> (/Users/olegb/Documents/GitHub/edge/test/103_net2node.js:167:3)
      at Test.Runnable.run (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runnable.js:233:15)
      at Runner.runTest (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:387:10)
      at /Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:470:12
      at next (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:312:14)
      at /Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:322:7
      at next (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:257:23)
      at Immediate._onImmediate (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runner.js:289:5)
      at processImmediate [as _immediateCallback] (timers.js:358:17)

  3) call patterns successfuly marshals .net exception thrown on CLR thread from exported CLR lambda:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (/Users/olegb/Documents/GitHub/edge/node_modules/mocha/lib/runnable.js:170:19)
      at Timer.listOnTimeout (timers.js:110:15)

**Comment by tjanczuk** [comment]
Which Node.js version are you using?

**Comment by OlegBoulanov** [comment]
v0.12.0
