### ISSUE TITLE
Unable to specify T-SQL source code dynamically (as argument, not comment or string)

### ISSUE THREAD

**Issue by mzahor** [tjanczuk/edge#277]
Basically I need to wrap edge.js's func into a promise. I'm trying smth like this:

```
var execSql = function(sql) {
    return function(sql) {
        var deferred = Q.defer();
        edge.func('sql', {
            source: sql
        })(null, function(error, result) {
            if (error) {
                deferred.reject(error);
            }
            deferred.resolve(result);
        });
        return deferred.promise;
    }
};
```

But it's failing with the following error:

```
c:\services\notification\notification-service\node_modules\edge\lib\edge.js:106
        throw new Error('Provide DLL or source file name or .NET script litera
              ^
Error: Provide DLL or source file name or .NET script literal as a string parmeter, or specify an options object with assemblyFile or source string property.
    at Object.exports.func (c:\services\notification\notification-service\node_modules\edge\lib\edge.js:106:15)
    at Object.getCustomersCount (c:\services\notification\notification-service\qhdb.js:8:14)
    at Object.<anonymous> (c:\services\notification\notification-service\test.js:3:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Is there any workaround for achieving such behavior or it's some kind of system limitation?

**Comment by eblumenfeld** [comment]
Hi mzahor:

We solved the same issue by creating the edge function in a variable **before** the promise:


var execsql = function(query,par){
   var edgefunc = edge.func('sql', {source: query})
	var deferred = $q.defer();
	edgefunc(par, function (err, data){
		if (err) {
		deferred.reject(err)
	} else {
		deferred.resolve(data)
		}
	});
	return deferred.promise;
}

**Comment by mzahor** [comment]
Thank you. Will try it.
