### ISSUE TITLE
Module load error on clean Windows 7 install

### ISSUE THREAD

**Issue by ivoloshin** [tjanczuk/edge#287]
I'm testing on a clean Windows 7 VM (64bit) and I get the following error:

```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
C:\Debug\edge\x86\edge.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Debug\edge\edge.js:41:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

I installed .NET 4.5.2 and latest node.js.

As a separate question, is there a way I can ship node.exe with my app so the user doesn't have to install it? If so, where would I put it? I'm assuming in the same folder as node.dll?

Thanks!

**Comment by ivoloshin** [comment]
Issue solved here: https://github.com/tjanczuk/edge/issues/280
