### ISSUE TITLE
failed to load assembly on azure

### ISSUE THREAD

**Issue by fraguada** [tjanczuk/edge#298]
Hello!  I've been using edge.js successfully locally and as a WebApp on Azure.  Now I need to update my app with some .dlls.  I have a working app (locally and on Azure) where the .dlls were compiled as Release/AnyCPU.  I need to now compile Release/x64.  In total there are three .dlls, two written in c# and one in c++.  As I mentioned, this works fine locally on a windows 7 x64 (WindowsNT 6.1.7601) machine.  When I try to run the deployment with the updated dlls compiled to Release/x64 I get the following error in my logs for the azure web app:

    Application has thrown an uncaught exception and is terminated:
    Error: Could not load file or assembly 'file:///D:\home\site\wwwroot\test.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
    at Error (native)
    at Object.exports.func (D:\home\site\wwwroot\node_modules\edge\lib\edge.js:154:17)
    at Object.<anonymous> (D:\home\site\wwwroot\index.js:2:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Program Files\iisnode\interceptor.js:451:1)

I've set the Azure WebApp platform setting to 64-bit (also tested with 32-bit, same error).  The Azure app is running on WindowsNT 6.2.9200 (Windows 8 or Server 2012).

Line 154 in edge.js is
`return edge.initializeClrFunc(options);`

My entry point is a js file as such:

    var edge = require('edge');
    var clrMethod = edge.func('test.dll'); //line 2 which is referenced in the error

    clrMethod("some input", function (error, result) {
        if (error) throw error;
        console.log(result);
	
    });

(this is a simplified 'minimum' just to test the functionality, the actual app, the one that works has more moving parts.  The file is index.js and the app is set up appropriately to look for this file as its entry point)

Again, this works fine on azure with the old dlls compiled to Release/AnyCPU, works file locally in any case, but is throwing this error if the .dlls are compiled in this manner.  There is new functionality in these .dlls that I can only access with this compilation flavor.

Any ideas of what could be the solution for this?

**Comment by fraguada** [comment]
In the end this turned out to be more of an issue with IISNode on Azure.  Since Azure only runs node x86 (no matter which platform you specify 32-bit or 64-bit), I was attempting to run another node.exe by pointing iisnode to the directory and specific exe of node I uploaded.  I noticed that even after changing the web.config file, Azure was still using the x86 installed version of node.  It was the iisnode.yml file which contained the pointer to the x86 node.js version.  After changing the iisnode.yml file to point to the x64 version of node.js, everything runs fine.
