### ISSUE TITLE
Can't build edge with node-gyp 3.x because delay load hook can't be compiled in C++/CLI binaries

### ISSUE THREAD

**Issue by paulcbetts** [tjanczuk/edge#320]
```
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  edge.cpp
  utils.cpp
  clrfunc.cpp
  clrfuncinvokecontext.cpp
  nodejsfunc.cpp
  nodejsfuncinvokecontext.cpp
  persistentdisposecontext.cpp
  clrfuncreflectionwrap.cpp
  v8synchronizationcontext.cpp
  clractioncontext.cpp
cl : Command line error D8045: cannot compile C file 'C:\Users\paulb\code\tinyspeck\slack-winssb\build\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c' with the /clr option [C:\Users\paulb\code\tinyspeck\slack-winssb\node_modules\edge-atom-shell\build\edge.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\paulb\code\tinyspeck\slack-winssb\build\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\paulb\\code\\tinyspeck\\slack-winssb\\build\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\paulb\code\tinyspeck\slack-winssb\node_modules\edge-atom-shell
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by blackshadev** [comment]
I have the exact same issue. I tried to update to nodejs 4.1.0.  Edge told me to that I needed to build edge on my own, for once node-gyp seemed to work, but failed at compiling `win_delay_load_hook.c`

**Comment by tjanczuk** [comment]
Edge.js does not yet support Node 4.x. Substantial work is required to port to new version of nan, which is what I am working on right now.

**Comment by paulcbetts** [comment]
> Edge.js does not yet support Node 4.x. Substantial work is required to port to new version of nan, which is what I am working on right now.

This actually hits even on node 0.12.x depending on the version of npm you're using to rebuild

**Comment by tebrevik** [comment]
I just managed to build successfully for 0.12.0 by modifying line 77 in binding.gyp from 
'AdditionalOptions': [ '/clr', '/wd4506' ]
to
'AdditionalOptions': [ '/TP /clr', '/wd4506' ]

**Comment by doruu12** [comment]
You can instruct binding.gyp not to use win_delay_load_hook https://github.com/doruu12/edge/commit/ce15b07e80d6a5cbbae6350be6f2e7be81e4198a

**Comment by paulcbetts** [comment]
Holy shit, that SHA1 is incredible

**Comment by tjanczuk** [comment]
:)

**Comment by tjanczuk** [comment]
I sell them for $1000 apiece
