### ISSUE TITLE
Edge installation is failing with node v4.1.2

### ISSUE THREAD

**Issue by zacharyabresch** [tjanczuk/edge#326]
I followed the instructions for installing `edge` on Mac OSX (10.10.4) but the `npm install edge` is failing with the following error:

```
> edge@4.0.0 install /Users/zabresch/Documents/8x8/scratching/c_to_dll/node_modules/edge
> node tools/install.js

  CXX(target) Release/obj.target/edge/src/mono/clractioncontext.o
  CXX(target) Release/obj.target/edge/src/mono/clrfunc.o
  CXX(target) Release/obj.target/edge/src/mono/clrfuncinvokecontext.o
  CXX(target) Release/obj.target/edge/src/mono/edge.o
  CXX(target) Release/obj.target/edge/src/mono/monoembedding.o
  CXX(target) Release/obj.target/edge/src/mono/task.o
  CXX(target) Release/obj.target/edge/src/mono/dictionary.o
  CXX(target) Release/obj.target/edge/src/mono/nodejsfunc.o
  CXX(target) Release/obj.target/edge/src/mono/nodejsfuncinvokecontext.o
  CXX(target) Release/obj.target/edge/src/mono/utils.o
  CXX(target) Release/obj.target/edge/src/common/v8synchronizationcontext.o
  SOLINK_MODULE(target) Release/edge.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/edge.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/zabresch/Documents/8x8/scratching/c_to_dll/node_modules/edge
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
edge@4.0.0 node_modules/edge
├── edge-cs@0.2.7
└── nan@2.1.0
```

I have no idea where to start troubleshooting this so _any_ help would be greatly appreciated. Thanks!

**Comment by johnleetechnology** [comment]
+1  same issue
