### ISSUE TITLE
Calling edge.func in Node REPL while using CoreCLR is broken

### ISSUE THREAD

**Issue by tjanczuk** [tjanczuk/edge#350]
References cannot be resolved: 

```
C:\projects\foo>node
>  var f = require('edge').func('async (i) => { return i.ToString(); }')
Error: Unable to resolve reference to System.Runtime.
    at Error (native)
    at Object.exports.func (C:\projects\edge\lib\edge.js:156:17)
    at repl:1:23
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
```

I believe it is because project.json.lock is not present in this case. @lstratman do you have a suggestion how to best address it?

**Comment by tjanczuk** [comment]
Foget it, I something else is wrong with my installation.
