### ISSUE TITLE
Sandboxing

### ISSUE THREAD

**Issue by amitavmohanty01** [tjanczuk/edge#356]
Objective: Execution of JS in node.js should be sandboxed.

I tried installed https://github.com/hflw/node-sandbox and https://github.com/gf3/sandbox yet requiring sandbox causes the following error.

```
Error: Cannot find module 'sandbox'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at eval (eval at <anonymous> (C:\Users\ammohant\Documents\Visual Studio 2015\Projects\edgejs_attempt\edgejs_attempt\bin\Debug\edge\double_edge.js:34:28), <anonymous>:5:13)
    at compileFunc (C:\Users\ammohant\Documents\Visual Studio 2015\Projects\edgejs_attempt\edgejs_attempt\bin\Debug\edge\double_edge.js:35:16)
```

I also tried https://github.com/tjanczuk/tripwire however requiring tripwire fails too with the following error.

```
Error: Cannot find module 'tripwire'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at eval (eval at <anonymous> (C:\Users\ammohant\Documents\Visual Studio 2015\Projects\edgejs_attempt\edgejs_attempt\bin\Debug\edge\double_edge.js:34:28), <anonymous>:3:28)
    at compileFunc (C:\Users\ammohant\Documents\Visual Studio 2015\Projects\edgejs_attempt\edgejs_attempt\bin\Debug\edge\double_edge.js:35:16)
```

What is the recommended way of sandboxing JS code called from C#?

**Comment by tjanczuk** [comment]
That depends on what you are trying to accomplish. Given you are considering to use node-sandbox, I would say you should consider not using Edge.js at all but instead spawning node.exe process from C# directly and run your Node.js code in it. (node-sandbox spawns child node processes).

**Comment by amitavmohanty01** [comment]
I might be looking at the wrong packages. Excuse my ignorance. What I am trying to do is run sandboxed JS code. We need to trigger the JS code from C# and most likely expose callbacks for JS to call C#. My previous issue was along the same lines. Edge.js solves the C# --> JS calling part nicely. As you explained the loop is completed by having callbacks. The next requirement that we have is to sandbox the JS code. Essentially we want to expose allowed functionality to JS via C# callbacks only.

**Comment by amitavmohanty01** [comment]
I tried using vm module from edge.js and it seems to work fine. However, when I attempt using vm2 module I am getting the following error.

```
Error: Cannot find module 'vm2'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at eval (eval at <anonymous> (C:\Users\ammohant\Documents\Visual Studio 2015\Projects\edgejs_attempt\edgejs_attempt\bin\Debug\edge\double_edge.js:34:28), <anonymous>:5:25)
```

Why am I getting load errors with so many external modules? I am doing all installations as global installations.

**Comment by shytikov** [comment]
Is it possible to run `edge.js` in AppDomain? And forbid internet access or filesystem access?
