### ISSUE TITLE
node-gyp fails on mac osx el capitan with only mono

### ISSUE THREAD

**Issue by jskrzypek** [tjanczuk/edge#386]
`which` doesn't return empty string when a command isn't found:
![jskrzypek_jss-macbook-pro____dev_tjanczuk_edge](https://cloud.githubusercontent.com/assets/1513265/12874641/007aa9fa-cde0-11e5-96aa-980cbc8f104b.png)

This means that node-gyp will think `dnx` is available, even when its not and you get this output/error:

```sh
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@4.2.6 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/jskrzypek/.nvm/versions/node/v4.2.6/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jskrzypek/dev/tjanczuk/edge/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jskrzypek/.nvm/versions/node/v4.2.6/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jskrzypek/.node-gyp/4.2.6/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jskrzypek/.node-gyp/4.2.6',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jskrzypek/.nvm/versions/node/v4.2.6/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jskrzypek/dev/tjanczuk/edge',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clrfunc.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clrfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/monoembedding.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/task.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/dictionary.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/nodejsfunc.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/nodejsfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/utils.o
  CXX(target) Release/obj.target/edge_nativeclr/src/common/edge.o
  SOLINK_MODULE(target) Release/edge_nativeclr.node
  CXX(target) Release/obj.target/edge_coreclr/src/common/v8synchronizationcontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/edge.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrembedding.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrfunc.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrnodejsfunc.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrnodejsfuncinvokecontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/utils.o
  SOLINK_MODULE(target) Release/edge_coreclr.node
  ACTION binding_gyp_build_managed_target_restore_packages src/CoreCLREmbedding/project.lock.json
bash: dnu: command not found
make: *** [src/CoreCLREmbedding/project.lock.json] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jskrzypek/.nvm/versions/node/v4.2.6/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/jskrzypek/.nvm/versions/node/v4.2.6/bin/node" "/Users/jskrzypek/.nvm/versions/node/v4.2.6/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Users/jskrzypek/dev/tjanczuk/edge
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
```

**Comment by jskrzypek** [comment]
After doing some digging and testing I realized that's not actually the whole issue. The problem is that the    output of `which` is going to be unreliable and what we really care about is the exit code, but GYP command expansions can't handle non-zero exit codes, so we have to consume it within the command expansion.

I know on a mac running zsh or bash it will work to change the conditions in the `binding.gyp` file to this form. I am not sure about other unix shells, however.

```gyp
...
'conditions': [
              [
                '"<!((which dnx) || echo not_found)"!="not_found"',
               { ...
```

**Comment by jskrzypek** [comment]
The whole `binding.gyp` file then becomes

```binding.gyp
##
# Portions Copyright (c) Microsoft Corporation. All rights reserved. 
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0  
#
# THIS CODE IS PROVIDED *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION 
# ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR 
# PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT. 
#
# See the Apache Version 2.0 License for specific language governing 
# permissions and limitations under the License.
##
{
  'targets': [
    {
      'target_name': 'edge_coreclr',
      'win_delay_load_hook': 'false',
      'include_dirs': [
        "<!(node -e \"require('nan')\")"
      ],
      'cflags+': [
        '-DHAVE_CORECLR -std=c++11'
      ],
      'xcode_settings': {
        'OTHER_CFLAGS': [
          '-DHAVE_CORECLR'
        ]
      },
      'conditions': [
        [
          'OS=="win"',
          {
            'conditions': [
              [
                '"<!(node -e "var whereis = require(\'./tools/whereis\'); console.log(whereis(\'dnx.exe\'));")"!=""',
                {
                  'sources+': [
                    'src/common/v8synchronizationcontext.cpp',
                    'src/common/edge.cpp',
                    'src/CoreCLREmbedding/coreclrembedding.cpp',
                    'src/CoreCLREmbedding/coreclrfunc.cpp',
                    'src/CoreCLREmbedding/coreclrnodejsfunc.cpp',
                    'src/CoreCLREmbedding/coreclrfuncinvokecontext.cpp',
                    'src/CoreCLREmbedding/coreclrnodejsfuncinvokecontext.cpp',
                    'src/common/utils.cpp'
                  ]
                },
                {
                  'type': 'none'
                }
              ]
            ]
          },
          {
            'conditions': [
              [
                '"<!((which dnx) || echo not_found)"!="not_found"',
                {
                  'sources+': [
                    'src/common/v8synchronizationcontext.cpp',
                    'src/common/edge.cpp',
                    'src/CoreCLREmbedding/coreclrembedding.cpp',
                    'src/CoreCLREmbedding/coreclrfunc.cpp',
                    'src/CoreCLREmbedding/coreclrnodejsfunc.cpp',
                    'src/CoreCLREmbedding/coreclrfuncinvokecontext.cpp',
                    'src/CoreCLREmbedding/coreclrnodejsfuncinvokecontext.cpp',
                    'src/common/utils.cpp'
                  ]
                },
                {
                  'type': 'none'
                }
              ]
            ]
          }
        ]
      ],
      'configurations': {
        'Release': {
          'msvs_settings': {
            'VCCLCompilerTool': {
              # this is out of range and will generate a warning and skip adding RuntimeLibrary property:
              'RuntimeLibrary': -1,
              # this is out of range and will generate a warning and skip adding RuntimeTypeInfo property:
              'RuntimeTypeInfo': -1,
              'BasicRuntimeChecks': -1,
              'ExceptionHandling': '0',
              'AdditionalOptions': [
                '/wd4506',
                '/DHAVE_CORECLR',
                '/EHsc'
              ]
            },
            'VCLinkerTool': {
              'AdditionalOptions': [
                '/ignore:4248',
                'shlwapi.lib'
              ]
            }
          }
        },
        'Debug': {
          'msvs_settings': {
            'VCCLCompilerTool': {
              # this is out of range and will generate a warning and skip adding RuntimeLibrary property:
              'RuntimeLibrary': 3,
              # this is out of range and will generate a warning and skip adding RuntimeTypeInfo property:
              'RuntimeTypeInfo': -1,
              'BasicRuntimeChecks': -1,
              'ExceptionHandling': '0',
              'AdditionalOptions': [
                '/wd4506',
                '/DHAVE_CORECLR',
                '/EHsc'
              ]
            },
            'VCLinkerTool': {
              'AdditionalOptions': [
                '/ignore:4248',
                'shlwapi.lib'
              ]
            }
          }
        }
      }
    },
    {
      'target_name': 'edge_nativeclr',
      'win_delay_load_hook': 'false',
      'include_dirs': [
        "<!(node -e \"require('nan')\")"
      ],
      'cflags+': [
        '-DHAVE_NATIVECLR -std=c++11'
      ],
      'xcode_settings': {
        'OTHER_CFLAGS': [
          '-DHAVE_NATIVECLR'
        ]
      },
      'conditions': [
        [
          'OS=="win"',
          {
            'sources+': [
              'src/dotnet/utils.cpp',
              'src/dotnet/clrfunc.cpp',
              'src/dotnet/clrfuncinvokecontext.cpp',
              'src/dotnet/nodejsfunc.cpp',
              'src/dotnet/nodejsfuncinvokecontext.cpp',
              'src/dotnet/persistentdisposecontext.cpp',
              'src/dotnet/clrfuncreflectionwrap.cpp',
              'src/dotnet/clractioncontext.cpp',
              'src/common/v8synchronizationcontext.cpp',
              'src/common/edge.cpp'
            ]
          },
          {
            'conditions': [
              [
                '"<!((which mono) || echo not_found)"!="not_found"',
                {
                  'sources+': [
                    'src/mono/clractioncontext.cpp',
                    'src/mono/clrfunc.cpp',
                    'src/mono/clrfuncinvokecontext.cpp',
                    'src/mono/monoembedding.cpp',
                    'src/mono/task.cpp',
                    'src/mono/dictionary.cpp',
                    'src/mono/nodejsfunc.cpp',
                    'src/mono/nodejsfuncinvokecontext.cpp',
                    'src/mono/utils.cpp',
                    'src/common/utils.cpp',
                    'src/common/v8synchronizationcontext.cpp',
                    'src/common/edge.cpp'
                  ],
                  'include_dirs': [
                    '<!@(pkg-config mono-2 --cflags-only-I | sed s/-I//g)'
                  ],
                  'link_settings': {
                    'libraries': [
                      '<!@(pkg-config mono-2 --libs)'
                    ],
                  }
                },
                {
                  'type': 'none'
                }
              ]
            ]
          }
        ]
      ],
      'configurations': {
        'Release': {
          'msvs_settings': {
            'VCCLCompilerTool': {
              # this is out of range and will generate a warning and skip adding RuntimeLibrary property:
              'RuntimeLibrary': -1,
              # this is out of range and will generate a warning and skip adding RuntimeTypeInfo property:
              'RuntimeTypeInfo': -1,
              'BasicRuntimeChecks': -1,
              'ExceptionHandling': '0',
              'AdditionalOptions': [
                '/clr',
                '/wd4506',
                '/DHAVE_NATIVECLR'
              ]
            },
            'VCLinkerTool': {
              'AdditionalOptions': [
                '/ignore:4248'
              ]
            }
          }
        },
        'Debug': {
          'msvs_settings': {
            'VCCLCompilerTool': {
              # this is out of range and will generate a warning and skip adding RuntimeLibrary property:
              'RuntimeLibrary': -1,
              # this is out of range and will generate a warning and skip adding RuntimeTypeInfo property:
              'RuntimeTypeInfo': -1,
              'BasicRuntimeChecks': -1,
              'ExceptionHandling': '0',
              'AdditionalOptions': [
                '/clr',
                '/wd4506',
                '/DHAVE_NATIVECLR'
              ]
            },
            'VCLinkerTool': {
              'AdditionalOptions': [
                '/ignore:4248'
              ]
            }
          }
        }
      }
    },
    {
      'target_name': 'build_managed',
      'type': 'none',
      'dependencies': [
        'edge_nativeclr',
        'edge_coreclr'
      ],
      'conditions': [
        [
          'OS=="win"',
          {
            'conditions': [
              [
                '"<!(node -e "var whereis = require(\'./tools/whereis\'); console.log(whereis(\'dnx.exe\'));")"!=""',
                {
                  'actions+': [
                    {
                      'action_name': 'compile_coreclr_embed',
                      'inputs': [
                        'src/CoreCLREmbedding/project.json'
                      ],
                      'outputs': [
                        'src/CoreCLREmbedding/bin/$(BUILDTYPE)/dnxcore50/CoreCLREmbedding.dll'
                      ],                        
                      'action': [
                        'cd "<(module_root_dir)\\src\\CoreCLREmbedding" & dnu restore & cd "<(module_root_dir)\\src\\CoreCLREmbedding" & dnu build --configuration $(Configuration) & copy "<(module_root_dir)\\src\\CoreCLREmbedding\\bin\\$(Configuration)\\dnxcore50\\CoreCLREmbedding.dll" "<(module_root_dir)\\build\\$(Configuration)"'
                      ]
                    }
                  ],
                  'copies+': [
                    {
                      'destination': '<(module_root_dir)\\build\\$(BUILDTYPE)',
                      'files': [
                        '<(module_root_dir)\\src\\CoreCLREmbedding\\bin\\$(BUILDTYPE)\\dnxcore50\\CoreCLREmbedding.dll'
                      ]
                    }
                  ]
                }
              ]
            ]
          },
          {
            'conditions': [
              [
                '"<!((which mono) || echo not_found)"!="not_found"',
                {
                  'actions+': [
                    {
                      'action_name': 'compile_mono_embed',
                      'inputs': [
                        'src/mono/*.cs'
                      ],
                      'outputs': [
                        'build/$(BUILDTYPE)/monoembedding.exe'
                      ],
                      'action': [
                        'dmcs',
                        '-sdk:4.5',
                        '-target:exe',
                        '-out:build/$(BUILDTYPE)/MonoEmbedding.exe',
                        'src/mono/*.cs',
                        'src/common/*.cs'
                      ]
                    }
                  ]
                }
              ],
              [
                '"<!((which dnx) || echo not_found)"!="not_found"',
                {
                  'actions+': [
                    {
                      'action_name': 'restore_packages',
                      'inputs': [
                        'src/CoreCLREmbedding/project.json'
                      ],
                      'outputs': [
                        'src/CoreCLREmbedding/project.lock.json'
                      ],
                      'action': [
                        'bash',
                        '-c',
                        'cd src/CoreCLREmbedding && dnu restore'
                      ]
                    },
                    {
                      'action_name': 'compile_coreclr_embed',
                      'inputs': [
                        'src/CoreCLREmbedding/*.cs',
                        'src/common/*.cs'
                      ],
                      'outputs': [
                        'src/CoreCLREmbedding/bin/$(BUILDTYPE)/dnxcore50/CoreCLREmbedding.dll'
                      ],                        
                      'action': [
                        'bash',
                        '-c',
                        'cd src/CoreCLREmbedding && dnu build --configuration $(BUILDTYPE)'
                      ]
                    }
                  ],
                  'copies+': [
                    {
                      'destination': '<(module_root_dir)/build/$(BUILDTYPE)',
                      'files': [
                        '<(module_root_dir)/src/CoreCLREmbedding/bin/$(BUILDTYPE)/dnxcore50/CoreCLREmbedding.dll',
                        '<(module_root_dir)/src/CoreCLREmbedding/project.json',
                        '<(module_root_dir)/src/CoreCLREmbedding/project.lock.json'
                      ]
                    }
                  ]
                }
              ]
            ]
          }
        ]
      ]
    }
  ]
}
```
