### ISSUE TITLE
Interfacing to Classes with non-Basic types.?? How??

### ISSUE THREAD

**Issue by kgentes** [tjanczuk/edge#473]
I have finally figured out how to install, build and use Edge for Windows (a few bugs in the process for ia32 needed to be worked around).  I have a 32bit assembly that I want to access and use.  I can now load the DLL and do a simple new on the Class constructor for the Widget Factory, but can't create the individual widget (instance from the factory).   Basically, this much of the code will run:
```
    var edge = require('edge');

    var helloWorld = edge.func(function () {/*
     async (input) => {
     return ".NET Welcomes " + input.ToString();
     }
     */});

    helloWorld('JavaScript', function (error, result) {
        if (error) throw error;
        console.log(result);
    });

    var newWidget = edge.func( {
        source: function () {/*

         using System.Collections.Generic;
         using System.Linq;
         using System.Text;
         using System.Runtime.InteropServices;
         using System.Windows;
         using System.Windows.Input;
         using Company.Launcher;

         async (dynamic data) =>
         {
             List<string> result = new List<string>();
             result.Add(data.beginText);

             IWidgetFactory WidgetFactory = new WidgetFactory();

             result.Add(data.endText);

             return result;
         }

         */},
        references: [ 'C:\\git\\widget\\Company.Launcher.dll'] }) ;

    var result = newWidget({ beginText: 'start', endText: 'DONE'  }, true);
    console.log('post NET result: ' + result);
```

However, when I use the factory's CreateNewWidget method, this code fails to work:
```
    var edge = require('edge');

    var helloWorld = edge.func(function () {/*
     async (input) => {
     return ".NET Welcomes " + input.ToString();
     }
     */});

    helloWorld('JavaScript', function (error, result) {
        if (error) throw error;
        console.log(result);
    });

    var newWidget = edge.func( {
        source: function () {/*

         using System.Collections.Generic;
         using System.Linq;
         using System.Text;
         using System.Runtime.InteropServices;
         using System.Windows;
         using System.Windows.Input;
         using Company.Launcher;

         async (dynamic data) =>
         {
             List<string> result = new List<string>();
             result.Add(data.beginText);

             IWidgetFactory WidgetFactory = new WidgetFactory();

             INewWidget newWidget = WidgetFactory.CreateNewWidget();

             result.Add(data.endText);

             return result;
         }

         */},
        references: [ 'C:\\git\\widget\\Company.Launcher.dll'] }) ;

    var result = newWidget({ beginText: 'start', endText: 'DONE'  }, true);
    console.log('post NET result: ' + result);
```

Instead, it generates this error:

```
C:\git\widget>node ServerSide\app.js
Load edge native library from: C:\git\widget\node_modules\edge\lib\native\win32\ia32\6.3.1\edge_nativeclr.node
edge::init
V8SynchronizationContext::Initialize
V8SynchronizationContext::Unref
ClrFunc::Initialize MethodInfo wrapper
ClrFunc::Initialize Func<object,Task<object>> wrapper
clrFuncProxy
ClrFunc::Call instance
ClrFuncInvokeContext::ClrFuncInvokeContext
ClrFuncInvokeContext::CompleteOnV8Thread
.NET Welcomes JavaScript
ClrFuncInvokeContext::DisposeCallback
ClrFuncInvokeContext::CompleteOnV8Thread - async with callback
ClrFunc::Initialize MethodInfo wrapper
ClrFunc::Initialize Func<object,Task<object>> wrapper
clrFuncProxy
ClrFunc::Call instance
ClrFuncInvokeContext::ClrFuncInvokeContext
ClrFuncInvokeContext::CompleteOnV8Thread
ClrFunc::MarshalCLRExceptionToV8
ClrFunc::MarshalCLRObjectToV8
ClrFunc::MarshalCLRExceptionToV8
ClrFunc::MarshalCLRObjectToV8
ClrFunc::MarshalCLRObjectToV8
ClrFunc::MarshalCLRObjectToV8
ClrFunc::MarshalCLRObjectToV8
ClrFunc::MarshalCLRObjectToV8
ClrFunc::MarshalCLRObjectToV8
ClrFunc::MarshalCLRExceptionToV8
ClrFunc::MarshalCLRObjectToV8
ClrFunc::MarshalCLRObjectToV8
ClrFunc::MarshalCLRObjectToV8
ClrFunc::MarshalCLRObjectToV8

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ClrFunc.MarshalCLRObjectToV8(Local<v8::Object>* , Object netdata)
   at ClrFunc.MarshalCLRToV8(Local<v8::Value>* , Object netdata)
   at ClrFunc.MarshalCLRObjectToV8(Local<v8::Object>* , Object netdata)
   at ClrFunc.MarshalCLRToV8(Local<v8::Value>* , Object netdata)
   at ClrFunc.MarshalCLRObjectToV8(Local<v8::Object>* , Object netdata)
   at ClrFunc.MarshalCLRToV8(Local<v8::Value>* , Object netdata)
   at ClrFunc.MarshalCLRToV8(Local<v8::Value>* , Object netdata)
   at ClrFunc.MarshalCLRObjectToV8(Local<v8::Object>* , Object netdata)
   at ClrFunc.MarshalCLRExceptionToV8(Local<v8::Value>* , Exception exception)
   at ClrFunc.Call(Local<v8::Value>* , Local<v8::Value> payload, Local<v8::Value> callback)
   at clrFuncProxy(FunctionCallbackInfo<v8::Value>* info)
   at Nan.imp.?A0x942b77c8.FunctionCallbackWrapper(FunctionCallbackInfo<v8::Value>* info)
```

The INewWidget object type is a complex type of multiple properties of various basic types (think struct).  I am guessing from the error that Edge doesn't like me trying to access that Class (although I can't understand why it lets me do a "new" on the IWidgetFactory type itself (that type has no properties, just two methods- although they are of complex types). 

Am I understanding the error above correctly?

Is it expect that we cannot access anything but basic types across the Node/.NET boundary?

**Comment by lstratman** [comment]
The stack trace and debug info indicate that Edge is actually having an issue trying to serialize an exception from the CLR back to Node.js, which indicates that something is going wrong within your method.  Can you wrap its contents in a try/catch block and have the catch `Console.WriteLine()` the exception message and the stack trace?  This will help us trace to the root of the problem.

**Comment by tjanczuk** [comment]
Cleaning up. Please reactivate if relevant details are available.
