### ISSUE TITLE
.

### ISSUE THREAD

**Issue by xdvarpunen** [tjanczuk/edge#474]

**Comment by xdvarpunen** [comment]
The bat file content needs to be updated since node.exe location is different depending on release version (0.10.0 is still there http://nodejs.org/dist/v0.10.0/node.exe but in v6.3.1 locatio changed to http://nodejs.org/dist/v6.3.1/win-x64/node.exe or http://nodejs.org/dist/v6.3.1/win-x86/node.exe

**Comment by xdvarpunen** [comment]
Test:

```cmd.exe
C:\edgething\node_modules\edge>tools\build.bat release 6.3.1
Downloading node.exe x86 6.3.1...
Trying download from http://nodejs.org/dist/v6.3.1/node.exe
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 104.20.23.46:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
 Cannot download node.exe x86 v6.3.1
Downloading node.exe x64 6.3.1...
Trying download from http://nodejs.org/dist/v6.3.1/x64/node.exe
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 104.20.23.46:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
 Cannot download node.exe x64 v6.3.1

```
