### ISSUE TITLE
Node=>.NET Core on Windows: Could not load file or assembly 'System.Runtime, Version=4.1.0.0...

### ISSUE THREAD

**Issue by pmunin** [tjanczuk/edge#496]
I just created super simple .NET Core class library using Visual Studio 2015. I try to use this class library in NodeJs app using edge and I get the following error:

```
c:\Users\pmunin\Documents\Visual Studio 2015\Projects\TestEdgeJsNodeToDotNetCore\src\node_modules\edge\lib\edge.js:171
    return edge.initializeClrFunc(options);
                ^
Error: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    at Error (native)
    at Object.exports.func (c:\Users\pmunin\Documents\Visual Studio 2015\Projects\TestEdgeJsNodeToDotNetCore\src\node_modules\edge\lib\edge.js:171:17)
    at Object.<anonymous> (c:\Users\pmunin\Documents\Visual Studio 2015\Projects\TestEdgeJsNodeToDotNetCore\src\index.js:14:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.runMain [as _onTimeout] (module.js:441:10)

```

Class library is based on default VS2015 project template: Class Library (.NET Core). All dependencies are default, no 3rd party dependencies.

server.js file is the following:

```
var clrMethod = edge.func({
    assemblyFile: 'TestEdgeJsNodeToDotNetCore.dll',
    typeName: 'TestEdgeJsNodeToDotNetCore.MyServiceFactory',
    methodName: 'Create' // This must be Func<object,Task<object>>
    ,references: [
        ("System.Runtime.dll")
    ] 
});

var factory = clrMethod();
```

here is project.json of .net class lib:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.6.0"
  },

  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }
}
```

What am I missing?

**Comment by raffaeler** [comment]
You have to always package the netcore libraries with nuget and the reference them.
In other words you cannot reference netcore libraries as you can do with the net framework (classic).
Look at this thread #463 for a detailed explanation.
