### ISSUE TITLE
Node.DLL not found in VS 2015

### ISSUE THREAD

**Issue by CodeLiftSleep** [tjanczuk/edge#501]
This is becoming very frustrating.  I am trying the sample project in VS2015. I have the C# project open and you can SEE I have the default edge NuGet package settings where it installs both the X64 and X86 directories in the project Edge directory AND I have them in BOTH the Bin/Debug and Bin/Release directories since I tried to build them both ways and STILL throwing a Node.dll cannot be found error when trying to compile. How the heck can it not find a file that is in the project??  

![image](https://cloud.githubusercontent.com/assets/17439424/19623200/e9a512ae-988e-11e6-87b6-3fcd6d4632d6.png)

Tried building in Any CPU and x86 and get the node.dll error.  Tried building in x64 nd get a systemwindowsforms.dll error...

![image](https://cloud.githubusercontent.com/assets/17439424/19623219/94848876-988f-11e6-954c-d92388365823.png)

**Comment by CodeLiftSleep** [comment]
This seems to be occurring because node-gyp build -debug keeps failing:

![image](https://cloud.githubusercontent.com/assets/17439424/19623730/c29ee53e-98a4-11e6-915d-554fdbb3491a.png)

**Comment by CodeLiftSleep** [comment]
Which is probably failing because node-gyp configure --ms_version=2015 is failing 
![image](https://cloud.githubusercontent.com/assets/17439424/19623803/9deb99ee-98a9-11e6-8ead-f0b68f791f00.png)

**Comment by CodeLiftSleep** [comment]
Getting this error and debug log while trying to run jsHint: 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'jshint' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose run-script [ 'prejshint', 'jshint', 'postjshint' ]
5 info lifecycle edge@6.5.1~prejshint: edge@6.5.1
6 silly lifecycle edge@6.5.1~prejshint: no script for prejshint, continuing
7 info lifecycle edge@6.5.1~jshint: edge@6.5.1
8 verbose lifecycle edge@6.5.1~jshint: unsafe-perm in lifecycle true
9 verbose lifecycle edge@6.5.1~jshint: PATH: C:\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\MNasty\node_modules\edge\node_modules\.bin;C:\Users\MNasty\node_modules\.bin;C:\nodejs;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Common Files\HP\Digital Imaging\bin;C:\Program Files (x86)\HP\Digital Imaging\bin\;C:\Program Files (x86)\HP\Digital Imaging\bin\Qt\Qt 4.3.3;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\IronRuby 1.1\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Sqllite;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\nodejs\;c:\users\mnasty\appdata\local\enthought\canopy\user\scripts;C:\Users\MNasty\AppData\Local\Enthought\Canopy\User;C:\Users\MNasty\AppData\Local\Enthought\Canopy\User\Scripts;C:\Microsoft VS Code\bin;C:\Users\MNasty\AppData\Roaming\npm
10 verbose lifecycle edge@6.5.1~jshint: CWD: C:\Users\MNasty\node_modules\edge
11 silly lifecycle edge@6.5.1~jshint: Args: [ '/d /s /c', 'node ./tools/runJsHint.js' ]
12 silly lifecycle edge@6.5.1~jshint: Returned: code: 1  signal: null
13 info lifecycle edge@6.5.1~jshint: Failed to exec jshint script
14 verbose stack Error: edge@6.5.1 jshint: `node ./tools/runJsHint.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid edge@6.5.1
16 verbose cwd C:\Users\MNasty\node_modules\edge
17 error Windows_NT 10.0.10586
18 error argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "jshint"
19 error node v6.5.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error edge@6.5.1 jshint: `node ./tools/runJsHint.js`
22 error Exit status 1
23 error Failed at the edge@6.5.1 jshint script 'node ./tools/runJsHint.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the edge package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./tools/runJsHint.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs edge
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls edge
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by CodeLiftSleep** [comment]
OK it appears the problem was related to node-gyp not being updated in npm to a version that could handle VS2015...so the FIRST thing you should recommend in big bold letters to anyone running Windows 10 and VS2015 is to update node-gyp because if not they won't be able to compile the build_double.bat file and will get the above happening...
