### ISSUE TITLE
TypeError: compiler.getBootstrapDependencyManifest is not a funct

### ISSUE THREAD

**Issue by neilyoung** [tjanczuk/edge#508]
Your sample:

    var edge = require('edge');
    
    var getTop10Products = edge.func('sql', function () {/*
        select top 10 * from Products
    */});
    
    getTop10Products(null, function (error, result) {
        if (error) throw error;
        console.log(result);
        console.log(result[0].ProductName);
        console.log(result[1].ReorderLevel);
    });
     
My result:

    /Users/me/Documents/sql/node_modules/edge/lib/edge.js:118
                options.bootstrapDependencyManifest = compiler.getBootstrapDependencyManifest();
                                                               ^
    
    TypeError: compiler.getBootstrapDependencyManifest is not a function
        at Object.exports.func (/Users/me/Documents/sql/node_modules/edge/lib/edge.js:118:60)
        at Object.<anonymous> (/Users/me/Documents/sql/sql.js:130:29)
        at Module._compile (module.js:556:32)
        at Object.Module._extensions..js (module.js:565:10)
        at Module.load (module.js:473:32)
        at tryModuleLoad (module.js:432:12)
        at Function.Module._load (module.js:424:3)
        at Module.runMain (module.js:590:10)
        at run (bootstrap_node.js:394:7)
        at startup (bootstrap_node.js:149:9)
        at bootstrap_node.js:509:3
    
The non-SQL samples work all fine. Ideas?

Is this the missing project.json?

**Comment by Hin-Fan** [comment]
As far as I can tell, Edge-sql is not written in .NET core, so it will not work through the .NET core path, which means it can only work under Windows at the moment.
