### ISSUE TITLE
Could not find file C:\Windows\TEMP\XXXXX.dll

### ISSUE THREAD

**Issue by mikeelston** [tjanczuk/edge#512]
Our Node app started experiencing this problem recently. 

I added EDGE_CS_TEMP_DIR config today to make sure that the problem wasn't some permissions issue with the Windows/TEMP directory but had same results.  

The current workaround is a reboot and it begins working as expected for a unknown time.

The error message in the log is:
> Application has thrown an uncaught exception and is terminated:
> Error: Could not find file 'C:\Program Files\[REDACTED]\[REDACTED]\cstemp\xa4dmbpy.dll'.
>     at Error (native)
>     at Object.exports.func (C:\Program Files\[REDACTED]\[REDACTED]\www\node_modules\edge\lib\edge.js:161:17)
>     at Object.<anonymous> (C:\Program Files\[REDACTED]\[REDACTED]\www\lib\sja.js:3:3011)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (C:\Program Files\[REDACTED]\[REDACTED]\www\routes\index.js:1:71)
> 

Windows 2008 R2 and iisnode. 
edge.js 6.5.1

**Comment by mikeelston** [comment]
I experienced this issue again over the weekend.  Has anyone else experienced this problem?

**Comment by mikeelston** [comment]
Issue happened again this weekend. Brand new install on windows 2012 R2 server,  no issue with memory or disk space.

**Comment by mikeelston** [comment]
We discovered a memory leak in a different IIS application that was wreaking havoc on all apps.  appears to not be a "Edge.js" specific issue
