### ISSUE TITLE
'glib.h' file not found

### ISSUE THREAD

**Issue by AlokBansal8** [tjanczuk/edge#527]
While installing edge I get following error:

```
Aloks-MacBook-Pro:Trial alok$ npm install -S edge

> edge-cs@1.2.1 install /Users/alok/Web/Trial/node_modules/edge-cs
> node tools/install.js


> edge@6.5.1 install /Users/alok/Web/Trial/node_modules/edge
> node tools/install.js

  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clrfunc.o
In file included from ../src/mono/clrfunc.cpp:4:
/usr/local/include/mono-2.0/mono/metadata/exception.h:4:10: fatal error: 'glib.h' file not found
#include <glib.h>
         ^
1 error generated.
make: *** [Release/obj.target/edge_nativeclr/src/mono/clrfunc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/alok/Web/Trial/node_modules/edge
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
trial@0.0.0 /Users/alok/Web/Trial
└─┬ edge@6.5.1 
  ├── edge-cs@1.2.1 
  └── nan@2.5.1 
```

Node Version 7.6.0
pkg-config-0.29.1_2
`mono -V` returns
```
Mono JIT compiler version 4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Mar  1 08:20:26 GMT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

**Comment by AlokBansal8** [comment]
@tjanczuk please help.

**Comment by mpayne-sds** [comment]
same here! been fighting this one for an hour now.

**Comment by gicquey** [comment]
Same here...

**Comment by hajikelist** [comment]
Same error now on Mac-OS El Capitan 10.11.2 
Mono 4.8.0

**Comment by akunkle** [comment]
This is caused by a change in Mono 4.8.  I downgraded to 4.6 and the problem went away.  The build scripts need to be changed before edge will work on 4.8.

**Comment by SeanSnyders** [comment]
@akunkle after not seeing any solution yet to the [issue](https://github.com/tjanczuk/edge/issues/529) of installing edge with only .Net Core, I also ran into the problems of Mono 4.8 and as you did, downgraded to 4.6 and then Edge installs fine on OSX 10.11.3.
