### ISSUE TITLE
not a valid Wind32 application error

### ISSUE THREAD

**Issue by angshuman** [tjanczuk/edge#552]
I am getting the following error with node 6.10.3 when running the first sample
I am trying to get desktop CLR to work with node.

node samples\101_hello_lambda.js

module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

**Error: %1 is not a valid Win32 application.**
\\?\C:\code\box\edge\build\Release\edge_coreclr.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\code\box\edge\lib\edge.js:52:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by santosedgar** [comment]
Have you found a solution? I'm stuck with the same error.

**Comment by buffcode** [comment]
Same error here ("ist keine zulässige Win32-Anwendung"/"not a valid Win32 application"):
![image](https://user-images.githubusercontent.com/2863518/27955961-b4f25a54-6317-11e7-99aa-d840393b9324.png)

Electron app compiled using Node 8.1.3 (Linux), target system running Node 8.1.3 as well but Windows.

**Comment by agracio** [comment]
For electron use `electron-edge` npm instead of `edge`

**Comment by chrisvanruiten** [comment]
A little bit late, but the problem on my side was building the application on a macOS. When I build it on a windows machine, it works fine. (Node 12.X and Electron 6.1.2)
