### ISSUE TITLE
Can't install with node 8.9.3

### ISSUE THREAD

**Issue by keyiis** [tjanczuk/edge#618]
I already install node-gyp and windows-build-tools,but still can't build edge
```
PS D:\work\nodejs\demo> .\node_modules\edge\tools\build.bat release 8.9.3
Building edge.node release for node.js x86 v8.9.3
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | ia32
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'D:\\work\\nodejs\\global_modules\\modules\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\work\\nodejs\\demo\\node_modules\\edge\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\work\\nodejs\\global_modules\\modules\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.node-gyp\\8.9.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.node-gyp\\8.9.3',
gyp info spawn args   '-Dnode_gyp_dir=D:\\work\\nodejs\\global_modules\\modules\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Administrator\\.node-gyp\\8.9.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\work\\nodejs\\demo\\node_modules\\edge',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\work\\nodejs\\demo\\node_modules\\edge\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
WTraceback (most recent call last):
  File "D:\work\nodejs\global_modules\modules\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\work\nodejs\global_modules\modules\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\work\nodejs\global_modules\modules\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\work\nodejs\global_modules\modules\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\work\nodejs\global_modules\modules\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2004, in GenerateOutput
    generator_flags))
  File "D:\work\nodejs\global_modules\modules\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 941, in _GenerateProject
    return _GenerateMSBuildProject(project, options, version, generator_flags)
  File "D:\work\nodejs\global_modules\modules\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 3313, in _GenerateMSBuildProject
    _FinalizeMSBuildSettings(spec, configuration)
  File "D:\work\nodejs\global_modules\modules\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 3014, in _FinalizeMSBuildSettings
    msbuild_settings = MSVSSettings.ConvertToMSBuildSettings(msvs_settings)
  File "D:\work\nodejs\global_modules\modules\node_modules\node-gyp\gyp\pylib\gyp\MSVSSettings.py", line 466, in ConvertToMSBuildSettings
    '%s' % (msvs_tool_name, msvs_setting, e))
IOError: [Errno 0] Error
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\work\nodejs\global_modules\modules\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\work\\nodejs\\demo\\node_modules\\edge\\lib\\native\\win32\\ia32\\8.9.3\\node.exe" "D:\\work\\nodejs\\global_modules\\modules\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--msvs_version=2015" "-release"
gyp ERR! cwd D:\work\nodejs\demo\node_modules\edge
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Error building edge.node release for node.js x86 v8.9.3
Building edge.node release for node.js x64 v8.9.3
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'D:\\work\\nodejs\\global_modules\\modules\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\work\\nodejs\\demo\\node_modules\\edge\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\work\\nodejs\\global_modules\\modules\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.node-gyp\\8.9.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.node-gyp\\8.9.3',
gyp info spawn args   '-Dnode_gyp_dir=D:\\work\\nodejs\\global_modules\\modules\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Administrator\\.node-gyp\\8.9.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\work\\nodejs\\demo\\node_modules\\edge',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\work\\nodejs\\demo\\node_modules\\edge\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/RuntimeLibrary to MSBuild, index value (-1) not in expected range [0, 4)
Warning: while converting VCCLCompilerTool/RuntimeTypeInfo to MSBuild, expected bool; got '-1'
Warning: while converting VCCLCompilerTool/BasicRuntimeChecks to MSBuild, index value (-1) not in expected range [0, 4)
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  utils.cpp
  clrfunc.cpp
  clrfuncinvokecontext.cpp
  nodejsfunc.cpp
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\nodejsfunc.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\nodejsfunc.cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\nodejsfunc.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\nodejsfunc.cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\utils.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\utils.cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\utils.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\utils.cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\clrfunc.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\clrfunc.cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\clrfuncinvokecontext.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\clrfuncinvokecontext.
  cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\clrfunc.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\clrfunc.cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\clrfuncinvokecontext.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\clrfuncinvokecontext.
  cpp)
  nodejsfuncinvokecontext.cpp
  persistentdisposecontext.cpp
  clrfuncreflectionwrap.cpp
..\src\dotnet\clrfunc.cpp(330): warning C4996: 'v8::Object::SetPrototype': 被声明为已否决 [D:\work\nodejs\demo\node_modules\edge
\build\edge_nativeclr.vcxproj]
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(3256): note: 参见“v8::Object::SetPrototype”的声明
  clractioncontext.cpp
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\nodejsfuncinvokecontext.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\nodejsfuncinvokeconte
  xt.cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\nodejsfuncinvokecontext.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\nodejsfuncinvokeconte
  xt.cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\persistentdisposecontext.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\persistentdisposecont
  ext.cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\persistentdisposecontext.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\persistentdisposecont
  ext.cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\clrfuncreflectionwrap.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4124): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\clrfuncreflectionwrap
  .cpp)
C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): error C2664: “std::pair<std::unique_ptr<const uint8_t [],std::default_d
elete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)”: 无法将参数 1 从“nullptr”转换为“nullp
tr &&” [D:\w
ork\nodejs\demo\node_modules\edge\build\edge_nativeclr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (编译源文件 ..\src\dotnet\clrfuncreflectionwrap.cpp)
  C:\Users\Administrator\.node-gyp\8.9.3\include\node\v8.h(4125): note: nullptr 只能转换成指针或句柄类型 (编译源文件 ..\src\dotnet\clrfuncreflectionwrap
  .cpp)
```

**Comment by tjanczuk** [comment]
Hello World!

**Comment by keyiis** [comment]
@tjanczuk can you tell what is causing this error?

**Comment by agracio** [comment]
@keyiis You can use `edge-js` fork that has support for Node.js 8.x and 9.x: https://github.com/agracio/edge-js
