### ISSUE TITLE
The JavaScript function was called synchronously but the underlying CLR function returned without completing the Task

### ISSUE THREAD

**Issue by ghost** [tjanczuk/edge#634]
I am using edge for the first time. I am getting this error:

> Error: The JavaScript function was called synchronously but the underlying CLR function returned without completing the Task. Call the JavaScript function asynchronously.
    at Error (native)
    at <anonymous>:1:55
    at Object.getQuestions (D:\repos\UQPipeline\MyService\dist\app\MyService\get-questions.js:36:16)
    at D:\repos\UQPipeline\MyService\dist\app\MyService\index.js:9:58
    at Layer.handle [as handle_request] (D:\repos\UQPipeline\MyService\dist\app\MyService\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\repos\UQPipeline\MyService\dist\app\MyService\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\repos\UQPipeline\MyService\dist\app\MyService\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\repos\UQPipeline\MyService\dist\app\MyService\node_modules\express\lib\router\layer.js:95:5)
    at D:\repos\UQPipeline\MyService\dist\app\MyService\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\repos\UQPipeline\MyService\dist\app\MyService\node_modules\express\lib\router\index.js:335:12)

Here is my js script:

```
    var _getQuestions = edge.func({
        source: function () {
            /*
            using ...

            public class Startup
            {
                const string environment = "...";
                public async Task<object> Invoke(dynamic input)
                {
                    var reader = new RecordReader(environment);
                    return await reader.Invoke(input);
                }
            }
            */
        },
        references: [
            __dirname + "\\bin\\....dll"
        ]
    });
```

and I have a unit test which I'm running in parallel and reports no problems:

```
        [TestMethod]
        public void GetsRecordSuccessfully()
        {
            RecordReader reader = new RecordReader("...");
            string url = "https://...";
            string[] questions = (string[])reader.Invoke(url).Result;
            Assert.IsNotNull(questions);
	}

```

**Comment by ctthang** [comment]
Removing async/await works for me
