### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'node.dll' from international folder

### ISSUE THREAD

**Issue by mfrisbey** [tjanczuk/edge#673]
A C# application consuming Edge.js crashes when running in a folder containing Asian characters. To reproduce the issue:

* Create a folder containing Japanese characters (example: カタカナ)
* Use Visual Studio (I used Visual Studio Community 2017) to create a new C# Windows Forms App inside this folder.
* Install version 8.2.1 of Edge.js using NuGet.
* Write simple code that scripts node.js code from C#. I used the sample code from the Edge.js readme to display a message from node.js code when the user clicks a button in the application.
* Run the application, ensuring that the node.js code executes.
* Note that the application encounters an exception:

```
System.DllNotFoundException: Unable to load DLL 'node.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at EdgeJs.Edge.NodeStartx64(Int32 argc, String[] argv)
   at EdgeJs.Edge.<>c__DisplayClass11_0.<Func>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

* Copy the visual studio project and all its code to a folder that _does not_ contain Japanese characters
* Build and run the application. Note that no exception is generated.

I'm running on Windows 10. I'd be happy to provide additional specs as needed.

I have a sample project that produces this issue - the .zip file is 50 MB. I can provide the project if requested, but it is easily recreated using the steps to reproduce.

**Comment by alphabin** [comment]
im having the same issue hope there is a resolution! I did install https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads and also node

```
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'node.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=EdgeJs
  StackTrace:
   at EdgeJs.Edge.NodeStartx86(Int32 argc, String[] argv)
   at EdgeJs.Edge.<>c__DisplayClass11_0.<Func>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by agracio** [comment]
These issues should be resolved in https://www.nuget.org/packages/EdgeJs
