### ISSUE TITLE
OSX node 11 installation fails because of the incompatibility with V8

### ISSUE THREAD

**Issue by knyga** [tjanczuk/edge#678]
Hi guys,
Installation fails on OSX:
```
> edge@7.10.1 install /Users/oknyga/www/shaman/shaman-converter2/node_modules/edge
> node tools/install.js

  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clrfunc.o
../src/mono/clrfunc.cpp:55:102: error: too few arguments to function call,
      expected at least 2, have 1
  ...codeFunction = v8::Local<v8::Function>::Cast(v8::Script::Compile(code)->...
                                                  ~~~~~~~~~~~~~~~~~~~     ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:1359:3: note: 'Compile'
      declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<Script> Compile(
  ^
../src/mono/clrfunc.cpp:73:46: warning: 'ToObject' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
    v8::Local<v8::Object> options = info[0]->ToObject();
                                             ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2549:10: note: 'ToObject' has
      been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:80:27: warning: 'Utf8Value' is deprecated: Use Isolate
      version [-Wdeprecated-declarations]
        String::Utf8Value assemblyFile(jsassemblyFile);
                          ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2991:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:81:27: warning: 'Utf8Value' is deprecated: Use Isolate
      version [-Wdeprecated-declarations]
        String::Utf8Value nativeTypeName(options->Get(Nan::New<v8::Strin...
                          ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2991:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:82:27: warning: 'Utf8Value' is deprecated: Use Isolate
      version [-Wdeprecated-declarations]
        String::Utf8Value nativeMethodName(options->Get(Nan::New<v8::Str...
                          ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2991:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:95:27: warning: 'Utf8Value' is deprecated: Use Isolate
      version [-Wdeprecated-declarations]
        String::Utf8Value compilerFile(options->Get(Nan::New<v8::String>...
                          ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2991:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:365:55: error: too few arguments to function call,
      expected 2, have 1
    result->SetPrototype(v8::Exception::Error(message));
    ~~~~~~~~~~~~~~~~~~~~                              ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:3548:3: note: 'SetPrototype'
      declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> SetPrototype(Local<Context> context,
  ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:418:31: note: expanded
      from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/mono/clrfunc.cpp:462:50: warning: 'ToObject' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
        v8::Local<v8::Object> jsbuffer = jsdata->ToObject();
                                                 ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2549:10: note: 'ToObject' has
      been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:482:32: warning: 'NumberValue' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
        double ticks = jsdate->NumberValue();
                               ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2569:3: note: 'NumberValue'
      has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", double NumberValue() const);
  ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:493:35: warning: 'Utf8Value' is deprecated: Use Isolate
      version [-Wdeprecated-declarations]
            v8::String::Utf8Value utf8name(name);
                                  ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2991:5: note: 'Utf8Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:505:30: warning: 'BooleanValue' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
        bool value = jsdata->BooleanValue();
                             ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2568:3: note: 'BooleanValue'
      has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
  ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:510:33: warning: 'Int32Value' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
        int32_t value = jsdata->Int32Value();
                                ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2572:3: note: 'Int32Value' has
      been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:515:34: warning: 'Uint32Value' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
        uint32_t value = jsdata->Uint32Value();
                                 ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2571:3: note: 'Uint32Value'
      has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/mono/clrfunc.cpp:520:32: warning: 'NumberValue' is deprecated: Use maybe
      version [-Wdeprecated-declarations]
        double value = jsdata->NumberValue();
                               ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8.h:2569:3: note: 'NumberValue'
      has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", double NumberValue() const);
  ^
/Users/oknyga/.node-gyp/11.12.0/include/node/v8config.h:326:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
12 warnings and 2 errors generated.
make: *** [Release/obj.target/edge_nativeclr/src/mono/clrfunc.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/11.12.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/oknyga/www/shaman/shaman-converter2/node_modules/edge
gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN proj@0.0.1 No repository field.
npm WARN proj@0.0.1 No license field.

+ edge@7.10.1
updated 1 package and audited 469 packages in 3.489s
found 0 vulnerabilities
```

OS Name:     Mac OS X
OS Version:  10.12
OS Platform: Darwin
node v11.12.0
mono v5.18.1
also .net core v2.1.505

During installation mono is enforced:
```PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig```

Would appreciate any suggestions.

**Comment by LuciferJun1227** [comment]
same issue

**Comment by mvohra708** [comment]
Same issue. Anyone found a solution to it yet?

**Comment by agracio** [comment]
https://github.com/agracio/edge-js is updated to support all new Node.js versions.
