### ISSUE TITLE
mono error on linux (centos)

### ISSUE THREAD

**Issue by cywang886** [tjanczuk/edge#682]
> node xxx.js

node_modules/edge/lib/edge.js:34
    throw new Error('The edge native module is not available at ' + builtEdge
    ^

Error: The edge native module is not available at /node_modules/edge/build/Release/edge_coreclr.node. You can use EDGE_NATIVE environment variable to provide alternate location of edge.node. If you need to build edge.node, follow build instructions for your platform at https://github.com/tjanczuk/edge
    at Object.<anonymous> (/node_modules/edge/lib/edge.js:34:11)    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by cywang886** [comment]
under nodejs v10.10.0
